services:
  web:
    build: .
    ports:
      - "8084:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
    container_name: ${CONTAINER_NAME:-amazon-clone}
    restart: unless-stopped
    networks:
      - app-network
    user: root

networks:
  app-network:
    driver: bridge 